[workspace]
authors = ["millennium-nova <s2111268@u.tsukuba.ac.jp>"]
channels = ["conda-forge"]
name = "terrafusion-demo"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.8"

[tasks]

[dependencies]
python = "3.10.*"
pytorch-gpu = "*"
cuda-version = "12.8.*"
flask = ">=3.1.2,<4"
numpy = ">=2.2.6,<3"
imageio = ">=2.37.0,<3"
diffusers = ">=0.35.2,<0.36"
accelerate = ">=1.12.0,<2"
transformers = ">=4.57.6,<5"
opencv = ">=4.12.0,<5"
